/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mohammed
 */
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.*;

import javax.swing.JOptionPane;
public class LoginPage extends javax.swing.JFrame{

   public static String string2=null;
   
    /**
     *
     */
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setTitle("Login");
        SecondPage secondpage= new SecondPage();
                
    }

    /**
     *
     * @param s
     */
    public void LOGIN(String s){
       string2=s;
       System.out.println(string2);
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        PASSWORD_FIELD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mohammed\\Documents\\NetBeansProjects\\Images\\src\\vigil_logo.jpg")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Password ");

        button1.setBackground(new java.awt.Color(204, 204, 204));
        button1.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        button1.setLabel("SUBMIT");
        button1.setPreferredSize(new java.awt.Dimension(74, 34));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        PASSWORD_FIELD.setText("jPasswordField1");
        PASSWORD_FIELD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PASSWORD_FIELDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(PASSWORD_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PASSWORD_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PASSWORD_FIELDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PASSWORD_FIELDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORD_FIELDKeyTyped

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       
            SecondPage secondpage= new SecondPage();
                      
              String psd = PASSWORD_FIELD.getText();
              LoginPage login = new LoginPage();
              
                //Login Page for Admin
             if(string2.contains("admin") && psd.equals("9876"))
             {
                {
                 System.out.println("TOUKA");
                 PASSWORD_FIELD.setText("");
                 LoginPage.this.setVisible(false);
                 Settings settingpage = new Settings();
                 settingpage.setVisible(true);
             } 
             }
             
              
              //Login Page for Super Admin
             else  if(string2.contains("sa") && (psd.equals("123456"))) 
                {
                 System.out.println("TOUKA");
                 PASSWORD_FIELD.setText("");
                 LoginPage.this.setVisible(false);
                 Settings settingpage = new Settings();
                 settingpage.setVisible(true);
             } 
            
      
              //Login Page for Client
                else  if(string2.contains("client") && (psd.contains("987654321"))){ 
                 System.out.println("TOUKA");
                 PASSWORD_FIELD.setText("");
                 LoginPage.this.setVisible(false);
                 Settings settingpage = new Settings();
                 settingpage.setVisible(true);}
                 
                
                   
               //Login Page for User
             else if(string2.contains("user") && psd.contains("123456789")){
      
                 System.out.println("TOUKA");
                 PASSWORD_FIELD.setText("");
                 LoginPage.this.setVisible(false);
                 Settings settingpage = new Settings();
                 settingpage.setVisible(true);
             }
              else{
                JOptionPane.showMessageDialog(rootPane, "wrong password");
             } 
            
             
            
             
    
           
              
    
             
    }//GEN-LAST:event_button1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    
       

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPasswordField PASSWORD_FIELD;
    public java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
