



/**
 *
 * @author mohammed
 */

public class SecondPage extends javax.swing.JFrame {

   public static String string1=null;
    
    
    public SecondPage() {
        initComponents();
    }
    
    public static void USER_NAME(String s){
        LoginPage login=new LoginPage();
        string1 = s;
        System.out.println(string1);
        login.LOGIN(string1);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ADMIN = new javax.swing.JButton();
        SUPER_ADMIN = new javax.swing.JButton();
        USER = new javax.swing.JButton();
        CLIENT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(225, 225, 325, 592));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mohammed\\Documents\\NetBeansProjects\\Images\\src\\vigil_logo.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 24, 449, 287));

        ADMIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADMIN.setText("ADMIN");
        ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINActionPerformed(evt);
            }
        });
        getContentPane().add(ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 180, 40));

        SUPER_ADMIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SUPER_ADMIN.setText("SUPER ADMIN");
        SUPER_ADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUPER_ADMINActionPerformed(evt);
            }
        });
        getContentPane().add(SUPER_ADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        USER.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        USER.setText("USER");
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });
        getContentPane().add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 456, 97, -1));

        CLIENT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CLIENT.setText("CLIENT");
        CLIENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIENTActionPerformed(evt);
            }
        });
        getContentPane().add(CLIENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 456, 163, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUPER_ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUPER_ADMINActionPerformed
        LoginPage login = new LoginPage();
        SecondPage.this.setVisible(false);
        login.setVisible(true);    
        SecondPage.USER_NAME("sa");

    }//GEN-LAST:event_SUPER_ADMINActionPerformed
   
   
       
    private void ADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINActionPerformed
        // Login page for Admin
        LoginPage login = new LoginPage();
        SecondPage.this.setVisible(false);
        login.setVisible(true);
        SecondPage.USER_NAME("admin");
        
    }//GEN-LAST:event_ADMINActionPerformed

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        //Login page for User
        LoginPage login = new LoginPage();
        SecondPage.this.setVisible(false);
        login.setVisible(true);
        SecondPage.USER_NAME("user");
    }//GEN-LAST:event_USERActionPerformed

    private void CLIENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIENTActionPerformed
        //Login Page for Client
        LoginPage login = new LoginPage();
        SecondPage.this.setVisible(false);
        login.setVisible(true);
        SecondPage.USER_NAME("client");
        
    }//GEN-LAST:event_CLIENTActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondPage().setVisible(true);
                new SecondPage().setSize(300,300);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ADMIN;
    private javax.swing.JButton CLIENT;
    public static javax.swing.JButton SUPER_ADMIN;
    private javax.swing.JButton USER;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
}
